version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: pip install --user -r requirements_windows.txt
          name: Pip install
      - run:
          command: python -m pytest -sv tests/ --tb=short
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
